### ISSUE TITLE
Toolbar Turns Green

### ISSUE THREAD

**Issue by MopsTMC** [dzwdz/microDurability#1]
Hello! I recently found out about your mod through the Fabric Discord and thought of it as a wonderful idea! So I went on and added it in a private modpack for a survival multiplayer server and noticed that when I wear (damaged) armor, everything above the hotbar and the armor slots in the inventory screen turn green when using a dark mode resource pack. The hue depends on what type of armor I'm wearing (Iron is pretty dark, Gold not as much). The rest of my friends who have the exact same mods haven't come across this. I am running _Minecraft 1.16.4_ with _Fabric Loader 0.10.8_ and using the following mods :

- Cinderscapes 1.2.4
- Dynamic FPS 1.2.1
- Fabric API 0.25.7
- FallingLeaves 1.1
- LamdDynamicLights 1.3.2
- Limitless 1.0.2
- Lithium 0.6.0
- microDurability 0.2.0
- ModMeny 1.14.9
- NotEnoughCrashes 2.1.4
- OkZoomer 4.0.1
- Phosphor 0.6.0
- ReplayMod 2.5.0
- FabricSeasons 1.0.1
- Sodium 0.1.0
- Terrestria 2.1.5 and
- Traverse 3.0.1
![In Server](https://user-images.githubusercontent.com/74558936/99289323-73778800-2845-11eb-9059-937aac3a32a8.png)
![Single-player](https://user-images.githubusercontent.com/74558936/99289332-770b0f00-2845-11eb-855d-4e8c71530e4c.png)
![with Dark Mode RP](https://user-images.githubusercontent.com/74558936/99289900-437cb480-2846-11eb-8d1c-6cf083bd0a5b.png)

I hope this issue can be solved cause I genuinely love this idea and its simplistic nature. I can provide more info and higher res screenshots if needed. Thanks ahead!

**Comment by dzwdz** [comment]
I'm unable to reproduce the issue, could you send me the resource pack that you're using?

**Comment by MopsTMC** [comment]
I use a combination of resource packs from [Vanilla Tweaks](https://vanillatweaks.net/picker/resource-packs/): 
[VanillaTweaks_15-11-20.zip](https://github.com/dzwdz/microDurability/files/5559855/VanillaTweaks_15-11-20.zip)
I tried removing the resource pack but I got the same result.

**Comment by MopsTMC** [comment]
Turns out some other mod is causing the issue. The armor slots and the crafting book change colors even without microDurability. I haven't had the time to investigate but I'll keep you updated.
