### ISSUE TITLE
Health and Armor bar disappear when holding item with durability under threshhold(shows warning sign)

### ISSUE THREAD

**Issue by JoeJoeTV** [dzwdz/microDurability#2]
__**Basic Info:**__
- Minecraft Version: 1.16.3
- Mod Version: 0.2.0
- Fabric Loader: 0.10.6
- Other Mods: https://pastebin.com/iRDFVVyT (NOTE: This is a list of all mods and libraries installed, which I got from a test crash-report, so I could get a list of mods in a simple way)

__**Issue:**__
When I hold any Tool, whose durability is under the set treshold, so it displays the warning sign under the crosshair, my Hears and Armor bar disappear.
It's probably a conflict with another mod, but I don't really know which one could cause it.

I hope this can be fixed or at least be found out, which mod causes this.

**Comment by dzwdz** [comment]
Could you verify that it works in [0.2.1](https://www.curseforge.com/minecraft/mc-mods/microdurability/download/3120646)?

**Comment by JoeJoeTV** [comment]
Thank you, it works with 0.2.1!
