### ISSUE TITLE
[Suggestion] Make durabilityless items show as full durability

### ISSUE THREAD

**Issue by IdrisQe** [dzwdz/microDurability#3]
Currently, items that can be worn which don't have durability (such as the Day Pack and other backpacks that go in the chest slot from Campanion) show on the micro hud as having 0 durability, which can cause brief moments of panic when you realize your armour is about to break, only to then remember it doesn't actually have durability.

It would be nice if these items could show as forever at a maximum of 0/0 instead of a minimum of 0/0!

**Comment by dzwdz** [comment]
Wouldn't it make more sense to just not show a durability bar at all?

**Comment by dzwdz** [comment]
fixed in 0.3.1, it should be up on curseforge soon
